### ISSUE TITLE
detected as a virus

### ISSUE THREAD

**Issue by ahahahaah** [i486/VxKex#16]
hello
i tryed to download the last release and avast blocks the download because of a virus detection.
how to be sure it is a false detection?

**Comment by CommonLoon102** [comment]
inspect the source code and compile yourself

**Comment by ahahahaah** [comment]
how to do this?

**Comment by CommonLoon102** [comment]
Learn C++

**Comment by ahahahaah** [comment]
learn c++ just to see if the antivirus displays a true or false notification?

**Comment by Theo1996** [comment]
virus scam

**Comment by ahahahaah** [comment]
> virus scam

so you confirm the avast alert?

**Comment by CommonLoon102** [comment]
> virus scam

What is the behavior of the virus? Have you reverse-engineered it? What does it exactly do?

**Comment by Theo1996** [comment]
@CommonLoon102 Look m8 after several proepr AV detect it specifically as a malware, and the repo has a bad history of scammers fakes, it is safe to say that is a virus and forget about it, since you are such a hackerman do all that work and check every line of binary for the greater good my fellow redditor *tips fedora*

**Comment by ahahahaah** [comment]
> > learn c++ just to see if the antivirus displays a true or false notification?
> 
> How else can you decide? There is no other way. 

antiviruses are created for this purpose (to avoid people learning programming languages each time they want to test a program) why ignore them?

**Comment by CommonLoon102** [comment]
It might be a virus. So what? What it is going to do? Are you logging in to your bank from Windows 7?
What if it is a virus? Don't you have backups? Do you have something to hide? And if yes, why you do it on Windows 7, which is closed-source and could be still a virus. Why don't you use Linux or FreeBSD then?

**Comment by ahahahaah** [comment]
> It might be a virus. So what? What if it is a virus?

lol, then i would simply, not use it. 
you really ask the question? the answer is not obvious?

**Comment by CommonLoon102** [comment]
> > It might be a virus. So what? What if it is a virus?
> 
> lol, then i would simply, not use it. you really ask the question? the answer is not obvious?

No, the answer is not so obvious. People are using malwares on a daily basis, like Microsoft Windows, Google-based Andoid devices, iOS, apps from Meta, etc.
Running one or more malware on you devices wouldn't really change much.

**Comment by ahahahaah** [comment]
> > > It might be a virus. So what? What if it is a virus?
> > 
> > 
> > lol, then i would simply, not use it. you really ask the question? the answer is not obvious?
> 
> No, the answer is not so obvious. People are using malwares on a daily basis, like Microsoft Windows, Google-based Android devices, iOS, apps from Meta, etc. Running one more malware on your device wouldn't really change much.



![image](https://github.com/user-attachments/assets/3ea085ff-10ec-4d10-a753-3fb56ee20941)
no way

**Comment by XP3410** [comment]
its so obvious that avast is shit

**Comment by Templayer** [comment]
I think this has been responded to adequately in https://github.com/i486/VxKex/issues/41#issuecomment-2558649899

**Comment by Sin-Shadow-Fox** [comment]
Currently waiting on official report from Avast as to the legitimacy of the information provided in https://github.com/i486/VxKex/issues/41#issuecomment-2558649899

**Comment by Sin-Shadow-Fox** [comment]
Update 12/30 2024: The information provided in https://github.com/i486/VxKex/issues/41#issuecomment-2558649899 does not pass avast's standards as shown in https://github.com/i486/VxKex/issues/55

**Comment by CommonLoon102** [comment]
Avast could check the source code and compile it...

**Comment by Neustradamus** [comment]
To follow this ticket.
