### ISSUE TITLE
Run the program through the Prompt (cmd.exe) with VxKex enabled

### ISSUE THREAD

**Issue by GregHouseMD** [i486/VxKex#23]
Hi.

Is it possible to run a program through the Prompt (cmd.exe) with VxKex enabled?

I use Windows 7.
I want to use a program that needs Windows 10 and the AVX2 instruction.
I'm trying to use VxKex for the Windows 10 issue and Intel SDE to emulate AVX2.

Thank you.

**Comment by i486** [comment]
Yes, you can run programs with VxKex enabled through cmd.exe. Two options are available:

- Enable VxKex for the specific program and launch it via cmd.exe as you normally would.
- Enable VxKex for cmd.exe itself and make sure "Disable VxKex for child processes" option is unchecked. This propagates VxKex functionality to all programs launched through cmd.exe.

**Comment by Neustradamus** [comment]
To follow this ticket.

**Comment by GregHouseMD** [comment]
> Yes, you can run programs with VxKex enabled through cmd.exe. Two options are available:
 
> * Enable VxKex for the specific program and launch it via cmd.exe as you normally would.

The program did not open, it displayed the error:

_pin.exe - Ponto de entrada não encontrado
Não foi possível localizar o ponto de entrada do procedimento GetSystemTimePreciseAsFileTime na biblioteca de vínculo dinâmico KERNEL32.dll._ 

> * Enable VxKex for cmd.exe itself and make sure "Disable VxKex for child processes" option is unchecked. This propagates VxKex functionality to all programs launched through cmd.exe.

I didn't find the option to enable VxKex in cmd.exe


I talked to the developer of the program and he told me that it won't work because the program uses many Windows 10 features that Windows 7 doesn't have.
The version of Qt that was used doesn't work on Windows 7.

Thank you for the help.

**Comment by Neustradamus** [comment]
GetSystemTimePreciseAsFileTime is linked to:
- https://github.com/YuZhouRen86/VxKex-NEXT/issues/214
- https://github.com/i486/VxKex/issues/23
- https://github.com/i486/VxKex/issues/196
