### ISSUE TITLE
Latest version not so clean.

### ISSUE THREAD

**Issue by Sin-Shadow-Fox** [i486/VxKex#26]
Just dropped off this supposed wonder cure to the Win7 blockade the tech industry has been putting up, specificlly [Version1.1.1.1375](https://github.com/i486/VxKex/releases/tag/Version1.1.1.1375) over at Avast and hoo boy does it look bad. Here's the email i got back (feel free to check out the virustotal link).

AVAST Support<customer.support@avast.com>
​
Hello Sin Shadow Fox, 

Thank you for contacting Avast and reporting a suspected false positive detection. I’m happy to help.  

Our technicians reviewed the detection and confirmed it as correct. Unfortunately, I am not able to provide any further information on this matter.

Virustotal.com report - https://www.virustotal.com/gui/file/652f6d2901c86de4a05743b5f808fafb6e28b9720c39bce5e7e031d26cac9035.

If you are the reported file owner and want to remove the detection, please make the necessary steps to review your file. Feel free to contact us again for a new analysis as soon as the file matches the [Avast Threat Labs - Clean guidelines](https://support.avast.com/article/threat-lab-clean-guideline) or  [Mobile application clean guidelines](https://support.avast.com/en-us/article/threat-lab-mobile-application-clean-guideline/#pc).

Thank you for understanding.

I hope you have a nice day and stay safe online.

Miro
Avast Customer Care Team

**Comment by CommonLoon102** [comment]
Even CrowdStrike Falcon doesn't detect it as a virus, so it isn't.

**Comment by Templayer** [comment]
I think this has been responded to adequately in https://github.com/i486/VxKex/issues/41#issuecomment-2558649899

**Comment by Sin-Shadow-Fox** [comment]
> I think this has been responded to adequately in [#41 (comment)](https://github.com/i486/VxKex/issues/41#issuecomment-2558649899)

We will find out when Avast gets back with the results after reviewing [i486](https://github.com/i486)'s information.

**Comment by Neustradamus** [comment]
To follow this ticket.
