### ISSUE TITLE
Vesion from KexSetup_Release_1_1_1_1375.exe does not work on Windows 7 32bit.

### ISSUE THREAD

**Issue by Sforsoft** [i486/VxKex#3]
It seems the VxKex does not work on Windows 7 x32 at all. If I enable VxKex for any application, windows 7 compatible or not , the execution always ends with BEX error.

After reverting to KexSetup_Release_1_1_0_1291.exe, the problem is gone.

**Comment by CommonLoon102** [comment]
Known issue. Latest version is not 32bit compatible.

**Comment by i486** [comment]
Fixed in latest official version.

https://github.com/i486/VxKex/releases/tag/Version1.1.2.1428

**Comment by Neustradamus** [comment]
To follow this ticket.
