### ISSUE TITLE
is there a portable version without installing VxKex?

### ISSUE THREAD

**Issue by candrapersada** [i486/VxKex#32]
is there a portable version without installing VxKex by just putting the VxKex file near the portable `mpv.exe`?

**Comment by i486** [comment]
There is no portable version.

**Comment by Half-Modern** [comment]
If you want to make a software work on Windows 7 request it from the author of this: https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7/ , maybe he could help.

**Comment by Neustradamus** [comment]
To follow this ticket.
