### ISSUE TITLE
Missing kxnt.dll

### ISSUE THREAD

**Issue by Komprogue** [i486/VxKex#45]
After installing the newest build of VxKex it breaks previous working one. 

Tried both updating from official build or clean install, but nothing works. 

![vxkex (2)](https://github.com/user-attachments/assets/09d147db-6216-4ae8-9389-9abfd113911a)
![vxkex (1)](https://github.com/user-attachments/assets/deae39a4-1c63-4bdb-a1a3-343b1be0b133)

**Comment by AbilioKID** [comment]
Check if all files are inside this folder:
```
C:\Program Files\VxKex
│   Application Compatibility List.docx
│   Changelog.txt
│   CpiwBp32.dll
│   CpiwBypa.dll
│   KexCfg.exe
│   KexSetup.exe
│   KexShl32.dll
│   KexShlEx.dll
│   VxKexLdr.exe
│   VxlView.exe
│   xxx.txt
│   
├───Kex32
│       dwrw10.dll
│       KxAdvapi.dll
│       KxBase.dll
│       KxCom.dll
│       KxCrt.dll
│       KxCryp.dll
│       KxDx.dll
│       KxMi.dll
│       KxNet.dll
│       KxNt.dll
│       KxUser.dll
│       mshtmlmedia.dll
│       ucrtbase.dll
│       
└───Kex64
        dwrw10.dll
        KxAdvapi.dll
        KxBase.dll
        KxCom.dll
        KxCrt.dll
        KxCryp.dll
        KxDx.dll
        KxMi.dll
        KxNet.dll
        KxNt.dll
        KxUser.dll
        KxUser_.dll
        mfdevmgr.dll
        ucrtbase.dllC:.
│   Application Compatibility List.docx
│   Changelog.txt
│   CpiwBp32.dll
│   CpiwBypa.dll
│   KexCfg.exe
│   KexSetup.exe
│   KexShl32.dll
│   KexShlEx.dll
│   VxKexLdr.exe
│   VxlView.exe
│   xxx.txt
│   
├───Kex32
│       dwrw10.dll
│       KxAdvapi.dll
│       KxBase.dll
│       KxCom.dll
│       KxCrt.dll
│       KxCryp.dll
│       KxDx.dll
│       KxMi.dll
│       KxNet.dll
│       KxNt.dll
│       KxUser.dll
│       mshtmlmedia.dll
│       ucrtbase.dll
│       
└───Kex64
        dwrw10.dll
        KxAdvapi.dll
        KxBase.dll
        KxCom.dll
        KxCrt.dll
        KxCryp.dll
        KxDx.dll
        KxMi.dll
        KxNet.dll
        KxNt.dll
        KxUser.dll
        KxUser_.dll
        mfdevmgr.dll
        ucrtbase.dll
```

**Comment by Komprogue** [comment]
> Check if all files are inside this folder:
> 
> ```
> C:\Program Files\VxKex
> │   Application Compatibility List.docx
> │   Changelog.txt
> │   CpiwBp32.dll
> │   CpiwBypa.dll
> │   KexCfg.exe
> │   KexSetup.exe
> │   KexShl32.dll
> │   KexShlEx.dll
> │   VxKexLdr.exe
> │   VxlView.exe
> │   xxx.txt
> │   
> ├───Kex32
> │       dwrw10.dll
> │       KxAdvapi.dll
> │       KxBase.dll
> │       KxCom.dll
> │       KxCrt.dll
> │       KxCryp.dll
> │       KxDx.dll
> │       KxMi.dll
> │       KxNet.dll
> │       KxNt.dll
> │       KxUser.dll
> │       mshtmlmedia.dll
> │       ucrtbase.dll
> │       
> └───Kex64
>         dwrw10.dll
>         KxAdvapi.dll
>         KxBase.dll
>         KxCom.dll
>         KxCrt.dll
>         KxCryp.dll
>         KxDx.dll
>         KxMi.dll
>         KxNet.dll
>         KxNt.dll
>         KxUser.dll
>         KxUser_.dll
>         mfdevmgr.dll
>         ucrtbase.dllC:.
> │   Application Compatibility List.docx
> │   Changelog.txt
> │   CpiwBp32.dll
> │   CpiwBypa.dll
> │   KexCfg.exe
> │   KexSetup.exe
> │   KexShl32.dll
> │   KexShlEx.dll
> │   VxKexLdr.exe
> │   VxlView.exe
> │   xxx.txt
> │   
> ├───Kex32
> │       dwrw10.dll
> │       KxAdvapi.dll
> │       KxBase.dll
> │       KxCom.dll
> │       KxCrt.dll
> │       KxCryp.dll
> │       KxDx.dll
> │       KxMi.dll
> │       KxNet.dll
> │       KxNt.dll
> │       KxUser.dll
> │       mshtmlmedia.dll
> │       ucrtbase.dll
> │       
> └───Kex64
>         dwrw10.dll
>         KxAdvapi.dll
>         KxBase.dll
>         KxCom.dll
>         KxCrt.dll
>         KxCryp.dll
>         KxDx.dll
>         KxMi.dll
>         KxNet.dll
>         KxNt.dll
>         KxUser.dll
>         KxUser_.dll
>         mfdevmgr.dll
>         ucrtbase.dll
> ```

All files/dll's are presented, none of them are actually missing. 

![dll's (1)](https://github.com/user-attachments/assets/a929bd3d-86ae-47fe-894c-b633e887a062)
![dll's (2)](https://github.com/user-attachments/assets/8491bf74-7746-431b-973a-867630dc8f35)

**Comment by i486** [comment]
When you mention the new build, are you referring to this release? https://github.com/i486/VxKex/releases/tag/Version1.1.2.1428.

I’m currently using QBT 5.0.3, and it works fine across all VxKex versions, including 1.1.2.

Have you tried downgrading to version 1.1.1 to see if that resolves the issue?

Additionally, it might help if you upload the log file located at `%LOCALAPPDATA%\VxKex\Logs\`

**Comment by Komprogue** [comment]
> When you mention the new build, are you referring to this release? https://github.com/i486/VxKex/releases/tag/Version1.1.2.1428.

Exactly this one. 

> I’m currently using QBT 5.0.3, and it works fine across all VxKex versions, including 1.1.2.

QBT here is just for example. After update/fresh installing v. 1.1.2.1428 it gives this missing .dll error message after launching every app and VxKex doesn't work anymore. 

> Have you tried downgrading to version 1.1.1 to see if that resolves the issue?

Sure, that's the only way to make it work again. 

> Additionally, it might help if you upload the log file located at `%LOCALAPPDATA%\VxKex\Logs\`

[qbittorrent.zip](https://github.com/user-attachments/files/18241457/qbittorrent.zip)

**Comment by i486** [comment]
Could you try this one and see if it makes difference?

https://www.mirrored.to/files/1SIBVZQO/KexSetup_Release_1_1_2_1428.rar_links

**Comment by Komprogue** [comment]
> Could you try this one and see if it makes difference?
> 
> https://www.mirrored.to/files/1SIBVZQO/KexSetup_Release_1_1_2_1428.rar_links

I accidentally uploaded the wrong log from working v. 1.1.1, now changed it to the right errored one, so redownload it, please.

**Comment by i486** [comment]
Could you run this batch script to share your %PATH% environment variable? It will generate a file named path_variables.txt in the same folder where the script is executed.

```
@echo off
setlocal

:: Create or overwrite the output file
set "output_file=%~dp0path_variables.txt"
echo Environment PATH Variables > "%output_file%"
echo Exported on: %date% at %time% >> "%output_file%"
echo. >> "%output_file%"

echo User PATH Environment Variable:
echo -------------------------------
echo User PATH Environment Variable: >> "%output_file%"
echo ------------------------------- >> "%output_file%"
for /f "tokens=2*" %%a in ('reg query "HKEY_CURRENT_USER\Environment" /v PATH 2^>nul') do (
    echo %%b
    echo %%b >> "%output_file%"
)

echo.
echo System PATH Environment Variable:
echo -------------------------------
echo. >> "%output_file%"
echo System PATH Environment Variable: >> "%output_file%"
echo ------------------------------- >> "%output_file%"
for /f "tokens=2*" %%a in ('reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v PATH 2^>nul') do (
    echo %%b
    echo %%b >> "%output_file%"
)

echo.
echo Results have been saved to: %output_file%
echo.
endlocal
pause
```

**Comment by Komprogue** [comment]
> Could you run this batch script to share your %PATH% environment variable? It will generate a file named path_variables.txt in the same folder where the script is executed.
> 
> ```
> @echo off
> setlocal
> 
> :: Create or overwrite the output file
> set "output_file=%~dp0path_variables.txt"
> echo Environment PATH Variables > "%output_file%"
> echo Exported on: %date% at %time% >> "%output_file%"
> echo. >> "%output_file%"
> 
> echo User PATH Environment Variable:
> echo -------------------------------
> echo User PATH Environment Variable: >> "%output_file%"
> echo ------------------------------- >> "%output_file%"
> for /f "tokens=2*" %%a in ('reg query "HKEY_CURRENT_USER\Environment" /v PATH 2^>nul') do (
>     echo %%b
>     echo %%b >> "%output_file%"
> )
> 
> echo.
> echo System PATH Environment Variable:
> echo -------------------------------
> echo. >> "%output_file%"
> echo System PATH Environment Variable: >> "%output_file%"
> echo ------------------------------- >> "%output_file%"
> for /f "tokens=2*" %%a in ('reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v PATH 2^>nul') do (
>     echo %%b
>     echo %%b >> "%output_file%"
> )
> 
> echo.
> echo Results have been saved to: %output_file%
> echo.
> endlocal
> pause
> ```

Done, but there's nothing. 

[path_variables.txt](https://github.com/user-attachments/files/18246929/path_variables.txt)

**Comment by i486** [comment]
How about?

`echo %PATH% > mypath.txt`

mypath.txt will be created in %USERPROFILE%

**Comment by Komprogue** [comment]
> How about?
> 
> `echo %PATH% > mypath.txt`
> 
> mypath.txt will be created in %USERPROFILE%

Here it is, though don't know how it could help. 

[mypath.zip](https://github.com/user-attachments/files/18247095/mypath.zip)

**Comment by i486** [comment]
> > How about?
> > `echo %PATH% > mypath.txt`
> > mypath.txt will be created in %USERPROFILE%
> 
> Here it is, though don't know how it could help.
> 
> [mypath.zip](https://github.com/user-attachments/files/18247095/mypath.zip)

I was trying to check your exact PATH variables to see if I could reproduce the error on my own system. Unfortunately, I couldn’t recreate the issue on either my Windows 7 PC or my virtual machine.

That said, it looks like your PATH might be messed up. Give this guide a try to fix the SYSTEM PATH and see if it resolves the issue.

> 1. **Open System Properties**:
>    - Right-click `Computer` or `My Computer` and select **Properties**.
>    - Click **Advanced system settings** on the left-hand side.
>    
> 2. **Open Environment Variables**:
>    - In the System Properties window, click the **Environment Variables** button.
> 
> 3. **Edit the PATH Variable**
> - **In the System Variables Section**:
>   - Locate the `Path` variable.
>   - Select it and click **Edit**.
> 
> - **Restore Default PATH**:
>   - ```
>     %SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
>     ```
> 
> 4. **Save Changes**
>    - After editing the PATH variable, click **OK** in all open dialogs to save your changes.
>    
> 5. **Restart your computer**

**Comment by Komprogue** [comment]
> > > How about?
> > > `echo %PATH% > mypath.txt`
> > > mypath.txt will be created in %USERPROFILE%
> > 
> > 
> > Here it is, though don't know how it could help.
> > [mypath.zip](https://github.com/user-attachments/files/18247095/mypath.zip)
> 
> I was trying to check your exact PATH variables to see if I could reproduce the error on my own system. Unfortunately, I couldn’t recreate the issue on either my Windows 7 PC or my virtual machine.
> 
> That said, it looks like your PATH might be messed up. Give this guide a try to fix the SYSTEM PATH and see if it resolves the issue.
> 
> > 1. **Open System Properties**:
> >    
> >    * Right-click `Computer` or `My Computer` and select **Properties**.
> >    * Click **Advanced system settings** on the left-hand side.
> > 2. **Open Environment Variables**:
> >    
> >    * In the System Properties window, click the **Environment Variables** button.
> > 3. **Edit the PATH Variable**
> > 
> > 
> > * **In the System Variables Section**:
> >   
> >   * Locate the `Path` variable.
> >   * Select it and click **Edit**.
> > * **Restore Default PATH**:
> >   
> >   * ```
> >     %SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
> >     ```
> > 
> > 
> > 4. **Save Changes**
> >    
> >    * After editing the PATH variable, click **OK** in all open dialogs to save your changes.
> > 5. **Restart your computer**

O.K., so now it's working without any problems. 
Seems like I accidently messed up system PATH (changed to ffmpeg) couple of weeks ago.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/i486/VxKex/issues/87
- https://github.com/i486/VxKex/issues/63
- https://github.com/i486/VxKex/issues/45
- https://github.com/i486/VxKex/issues/19

For the moment, you can use:
- https://github.com/YuZhouRen86/VxKex-NEXT

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/i486/VxKex/issues/87
- https://github.com/i486/VxKex/issues/63
- https://github.com/i486/VxKex/issues/45
- https://github.com/i486/VxKex/issues/19
- https://github.com/i486/VxKex/issues/11

For the moment, you can use:
- https://github.com/YuZhouRen86/VxKex-NEXT
