### ISSUE TITLE
Will this work with drivers?

### ISSUE THREAD

**Issue by MarioNooo** [i486/VxKex#5]
I managed to install Windows 7 on a Asus Prime B550M-A motherboard. It included NVMe drivers and USB 3.0 drivers. But can I use this to install the rest of the drivers?

**Comment by i486** [comment]
No, this isn't intended for drivers.
However, you can find almost every driver you need on https://winraid.level1techs.com/. 
You’ll just need to put in some time to research.

**Comment by defautluser0** [comment]
you can also use [sdi](https://sdi-tool.org) to get drivers (assuming there are windows 7 drivers for your computer in the driverpacks for it). you may need to download network drivers on another computer before downloading the rest on that computer if your windows 7 install doesnt have any wifi/ethernet drivers

**Comment by Neustradamus** [comment]
To follow this ticket.
