### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by tahaghafuri** [i486/VxKex#50]
@i486 The https://github.com/vxiiduu was reserved to prevent abuse by fraudsters and a link was given to this project.

**Comment by skibidivxiiduu** [comment]
do not spread information stupid idiot i just changed my name because im good guy

**Comment by skibidivxiiduu** [comment]
also he deleted his account because he got doxed

**Comment by YuZhouRen86** [comment]
> also he deleted his account because he got doxed 

Ok. Thank you for the contribution to VxKex development, but use vxiiduu username and put a story without additional explanation is disrespectful to the original author. The others will think you are faking vxiiduu and faking a story about him.

**Comment by tahaghafuri** [comment]
> also he deleted his account because he got doxed

Okay, Master Child. Anyway, I reserved that username so it won't be misused again.

**Comment by Neustradamus** [comment]
To follow this ticket.
