### ISSUE TITLE
windows server 2008 support

### ISSUE THREAD

**Issue by Vista6003** [i486/VxKex#8]
Hi. can i install this on windows server 2008?
will it work? i heard 7 and server 2008 or based on the same codebase

**Comment by hubstedt** [comment]
I haven't tried but I would expect it to work the same.

**Comment by i486** [comment]
I haven’t tested it, but if it does work, it would need to be on Windows Server 2008 R2 rather than Windows Server 2008, as the latter is essentially the server version of Vista. Maybe you can test it and let us know how it goes.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/i486/VxKex/issues/108
